server:
  port: 8082

spring:

  datasource:
    url: "jdbc:mysql://localhost:3306/smarttrack?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer