server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smarttrack?useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always
